services:
  web:
    build: .
    container_name: web
    command: >
      sh -c "python manage.py collectstatic --noinput && python manage.py makemigrations && python manage.py migrate && gunicorn core.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --workers 4"
    volumes:
      - .:/app
    expose:
      - "8000"
      # depends_on:
      # - redis
      # - db
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      # - REDIS_HOST=redis

  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      # - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - web
      # - db

      # db:
      #   image: postgres:15
      #   container_name: db
      #   restart: always
      #   environment:
      #     POSTGRES_DB: ${DB_NAME}
      #     POSTGRES_USER: ${DB_USER}
      #     POSTGRES_PASSWORD: ${DB_PASSWORD}
      #   volumes:
      #     - postgres_data:/var/lib/postgresql/data
      #   ports:
      #     - "5432:5432"

      # redis:
      #   image: redis:7
      #   container_name: redis
      #   ports:
      #     - "6380:6379"
      #     # - db

      # celery_worker:
      #   build: .
      #   container_name: celery_worker
      #   command: celery -A core worker -l info --pool=solo
      #   volumes:
      #     - .:/app
      #   working_dir: /app
      #   depends_on:
      #     - redis
      #     - web
      #   restart: always

      # celery_beat:
      #   build: .
      #   container_name: celery_beat
      #   command: celery -A core beat -l info
      #   volumes:
      #     - .:/app
      #   working_dir: /app
      #   depends_on:
      #     - redis
      #     - web
      #   restart: always


      # volumes:
      #   postgres_data:
